#!/bin/sh


yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.05           \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.97           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.5            \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# ==== yabai-spaces-widget stuff ====
signals=(
   "space_changed"
   "display_added"
   "display_removed"
   "display_moved"
   "display_changed"
   "mission_control_enter"
   "mission_control_exit"
)
for signal in "${signals[@]}"
do
   yabai --message signal \
         --add \
            event=$signal \
            action="osascript -e 'tell application \"Yabai Spaces Widget\" to refresh'"
done
# ====================================

echo "yabai configuration loaded.."

# =============== rules ==============
yabai -m rule --add app=WezTerm space=^1
yabai -m rule --add app=Terminal space=^1

yabai -m rule --add app=Arc space=^2
yabai -m rule --add app=Firefox space=^2

yabai -m rule --add title=WhatsApp space=^3
yabai -m rule --add app=Telegram space=^3
yabai -m rule --add app=Signal space=^3

yabai -m rule --add app=Mail space=^4
yabai -m rule --add app=Todoist space=^4

yabai -m rule --add app=Timemator space=^5
yabai -m rule --add app=Fantastical space=^5
yabai -m rule --add app=Calendar space=^5

yabai -m rule --add app=Obsidian space=^6

yabai -m rule --add app=Spotify space=^11

yabai -m rule --add app=DBeaver space=^7
yabai -m rule --add app=DataGrip space=^7

yabai -m rule --add app=PowerPoint space=^8

# =============== floating ============
yabai -m rule --add app=Flow manage=off
yabai -m rule --add app="Cisco AnyConnect" manage=off
yabai -m rule --add subrole="kAXSystemDialogSubrole" manage=off
yabai -m rule --add subrole="kAXSystemFloatingWindowSubrole" manage=off
yabai -m rule --add subrole="AXDialog" manage=off
yabai -m rule --add subrole="AXSystemDialog" manage=off
