#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width             3
bspc config window_gap               6
bspc config border_radius            4

bspc config focus_follows_pointer true

bspc config focused_border_color  "#a3be8c"
bspc config active_border_color   "#b48ead"
bspc config presel_feedback_color "#a3be8c"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
