#! /bin/sh

# Make hot-reload safe
bspc rule -r *:*

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0   -d I II III IV V
bspc monitor DP-2   -d  
bspc monitor HDMI-0 -d  

bspc config border_width             3
bspc config window_gap               6
bspc config border_radius            4

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config focused_border_color  "#a3be8c"
bspc config active_border_color   "#b48ead"
bspc config presel_feedback_color "#a3be8c"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Signal desktop='' follow=off focus=off
bspc rule -a TelegramDesktop desktop='' follow=off focus=off
bspc rule -a whatsapp-nativefier-d40211 desktop='' follow=off focus=off
bspc rule -a Spotify desktop='' follow=off focus=off
bspc rule -a thunderbird desktop='' follow=off focus=off

# Stuff that's always floating
floating=(alacritty-float 1Password Com.cisco.anyconnect.gui)
screenwidth=3440
screenheight=1440
windowwidth=$screenwidth/2
windowheight=$screenheight/2
windowx=$(($screenwidth/2 - $windowwidth/2))
windowy=$(($screenheight/2 - $windowheight/2))
echo "$windowwidth x $windowheight + $windowx + $windowy" > $HOME/floating.txt
for i in "${floating[@]}"; do
  bspc rule -a $i state=floating center=true follow=on focus=on; done

sxhkd &

# Autostart windows
autostart=(whatsapp-nativefier signal-desktop telegram-desktop thunderbird)
for prog in "${autostart[@]}"
do
  killall $prog &> /dev/null; $prog &> /dev/null &
done

