#!/bin/bash

# This script will open a project in a tmux session, or switch to an existing one if possible.

# Select a project
options=$(ls -d ~/Projects/* ~/Notes/* ~/Nextcloud/Uni/*)

selected="$(echo "$options" | fzf-tmux)"
if [ -z "$selected" ]; then
  exit 0
fi
name=$(basename "$selected" | sed 's/[ .-]/_/g' | tr '[:upper:]' '[:lower:]')

