#!/bin/zsh

# This creates/attaches to a tmux session named "base"

source ~/.zshrc

tmux has-session -t base
if [ $? -ne 0 ]; then
    tmux new -s base
fi

if [ -n "$TMUX" ]; then
  tmux switch-client -t base
else
  tmux attach-session -t base
fi

